### ISSUE TITLE
accountDatabase.txt syntax

### ISSUE THREAD

**Issue by pax** [connervieira/DropAuth#1]
there's no mention in the [DOCUMENTATION.md](https://github.com/connervieira/DropAuth/blob/main/DOCUMENTATION.md)  about the `accountDatabase.txt` syntax. An example would come handy.

**Comment by connervieira** [comment]
The database is just a serialized PHP array with a list of usernames, and their associated password hash. I've added some example code to the [DOCUMENATION.md](DOCUMENATION.md) file.
